name: order_master
description: Um programa de comanda de restaurante.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  cpf_cnpj_validator: ^2.0.0
  sqflite: ^2.3.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/LogoOrderMaster.jpg
    - images/LogoOrderMaster.png
    - images/LogoOrderMasterFinal.png

